spring.application.name=e-commorce.org

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=OGxE/14kQUIBN1c2YInLVB8PisM6Fp4Tbl9xPcQlfSM=
jwt.expiration=3600000 